/**
 * Template Metadata - 60+ templates with usage guidance
 */

import type { TemplateMetadata } from '../types';

export const TEMPLATES: TemplateMetadata[] = [
  // ============ Chart Templates ============
  {
    name: 'chart-bar-plain-text',
    category: 'chart',
    dataField: 'values',
    description: '水平条形图，适合类别对比',
    suitableFor: ['类别对比', '排名展示', '数值大小对比'],
    notSuitableFor: ['时间序列', '占比数据', '趋势变化'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-column-simple',
    category: 'chart',
    dataField: 'values',
    description: '垂直柱状图，适合离散数据对比',
    suitableFor: ['数值对比', '离散时间点', '类别对比'],
    notSuitableFor: ['连续趋势', '占比数据'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-line-plain-text',
    category: 'chart',
    dataField: 'values',
    description: '折线图，适合展示连续变化趋势',
    suitableFor: ['趋势变化', '时间序列', '连续数据'],
    notSuitableFor: ['类别对比', '占比数据', '无顺序数据'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-pie-plain-text',
    category: 'chart',
    dataField: 'values',
    description: '饼图，适合展示占比关系',
    suitableFor: ['占比关系', '部分与整体', '百分比'],
    notSuitableFor: ['趋势变化', '数值对比', '时间序列'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-pie-donut-plain-text',
    category: 'chart',
    dataField: 'values',
    description: '环形图，适合展示占比关系',
    suitableFor: ['占比关系', '部分与整体', '百分比'],
    notSuitableFor: ['趋势变化', '数值对比', '时间序列'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-pie-compact-card',
    category: 'chart',
    dataField: 'values',
    description: '紧凑饼图卡片',
    suitableFor: ['占比关系', '少量数据项'],
    notSuitableFor: ['趋势变化', '大量数据'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-pie-donut-pill-badge',
    category: 'chart',
    dataField: 'values',
    description: '带徽章的环形图',
    suitableFor: ['占比关系', '强调某项'],
    notSuitableFor: ['趋势变化', '数值对比'],
    requiredFields: ['label', 'value'],
    optionalFields: ['desc'],
  },
  {
    name: 'chart-wordcloud',
    category: 'chart',
    dataField: 'values',
    description: '词云图，适合展示关键词频率',
    suitableFor: ['关键词频率', '词频统计', '主题分布'],
    notSuitableFor: ['精确数值', '趋势变化', '对比分析'],
    requiredFields: ['label', 'value'],
    optionalFields: [],
  },

  // ============ List Templates ============
  {
    name: 'list-row-horizontal-icon-arrow',
    category: 'list',
    dataField: 'lists',
    description: '水平列表，带图标和箭头',
    suitableFor: ['并列要点', '少量项目（3-5个）', '步骤概览'],
    notSuitableFor: ['大量项目', '层级关系', '顺序流程'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon', 'value'],
  },
  {
    name: 'list-column-simple-vertical-arrow',
    category: 'list',
    dataField: 'lists',
    description: '垂直列表，带箭头',
    suitableFor: ['并列要点', '特征列举', '垂直展示'],
    notSuitableFor: ['顺序关系', '层级结构'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon', 'value'],
  },
  {
    name: 'list-column-vertical-icon-arrow',
    category: 'list',
    dataField: 'lists',
    description: '垂直列表，带图标和箭头',
    suitableFor: ['并列要点', '带图标的列表'],
    notSuitableFor: ['顺序关系', '层级结构'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon', 'value'],
  },
  {
    name: 'list-column-done-list',
    category: 'list',
    dataField: 'lists',
    description: '完成列表，带勾选标记',
    suitableFor: ['任务清单', '已完成事项', '检查列表'],
    notSuitableFor: ['数值对比', '流程展示'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'list-grid-badge-card',
    category: 'list',
    dataField: 'lists',
    description: '网格布局卡片',
    suitableFor: ['多维分类', '矩阵展示', '特征对比'],
    notSuitableFor: ['线性流程', '层级关系', '时间序列'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon', 'value'],
  },
  {
    name: 'list-grid-candy-card-lite',
    category: 'list',
    dataField: 'lists',
    description: '糖果风格网格卡片',
    suitableFor: ['轻量展示', '要点列举'],
    notSuitableFor: ['严肃场景', '数据分析'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon'],
  },
  {
    name: 'list-grid-ribbon-card',
    category: 'list',
    dataField: 'lists',
    description: '缎带风格网格卡片',
    suitableFor: ['特色展示', '要点列举'],
    notSuitableFor: ['数据分析', '流程展示'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon'],
  },
  {
    name: 'list-sector-plain-text',
    category: 'list',
    dataField: 'lists',
    description: '扇形布局',
    suitableFor: ['环形展示', '围绕中心主题'],
    notSuitableFor: ['线性流程', '数值对比'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'list-zigzag-down-compact-card',
    category: 'list',
    dataField: 'lists',
    description: '之字形向下布局',
    suitableFor: ['视觉丰富的列表', '交替展示'],
    notSuitableFor: ['严格顺序', '数值对比'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon'],
  },
  {
    name: 'list-zigzag-down-simple',
    category: 'list',
    dataField: 'lists',
    description: '简单之字形向下',
    suitableFor: ['交替展示', '要点列举'],
    notSuitableFor: ['严格顺序', '数值对比'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'list-zigzag-up-compact-card',
    category: 'list',
    dataField: 'lists',
    description: '之字形向上布局',
    suitableFor: ['视觉丰富的列表', '交替展示'],
    notSuitableFor: ['严格顺序', '数值对比'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon'],
  },
  {
    name: 'list-zigzag-up-simple',
    category: 'list',
    dataField: 'lists',
    description: '简单之字形向上',
    suitableFor: ['交替展示', '要点列举'],
    notSuitableFor: ['严格顺序', '数值对比'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },

  // ============ Sequence Templates ============
  {
    name: 'sequence-timeline-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '简单时间线',
    suitableFor: ['时间顺序', '历史事件', '发展阶段'],
    notSuitableFor: ['非时间顺序', '并列关系'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'time'],
  },
  {
    name: 'sequence-timeline-rounded-rect-node',
    category: 'sequence',
    dataField: 'sequences',
    description: '圆角节点时间线',
    suitableFor: ['时间顺序', '里程碑', '阶段展示'],
    notSuitableFor: ['非时间顺序', '并列关系'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'time'],
  },
  {
    name: 'sequence-steps-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '简单步骤流程',
    suitableFor: ['流程步骤', '操作指南', '先后顺序'],
    notSuitableFor: ['并列关系', '循环流程'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-funnel-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '漏斗图',
    suitableFor: ['转化过程', '逐级递减', '筛选流程'],
    notSuitableFor: ['非递减过程', '并列数据'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'value'],
  },
  {
    name: 'sequence-pyramid-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '金字塔图',
    suitableFor: ['层级递进', '基础到高级', '重要性排序'],
    notSuitableFor: ['并列关系', '时间序列'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-circular-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '环形流程',
    suitableFor: ['循环过程', '周期性流程', '闭环'],
    notSuitableFor: ['线性流程', '单向过程'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-roadmap-vertical-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '垂直路线图',
    suitableFor: ['规划展示', '发展路径', '阶段目标'],
    notSuitableFor: ['并列关系', '非顺序内容'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'time'],
  },
  {
    name: 'sequence-roadmap-vertical-plain-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '纯文字垂直路线图',
    suitableFor: ['规划展示', '发展路径'],
    notSuitableFor: ['并列关系', '非顺序内容'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'time'],
  },
  {
    name: 'sequence-snake-steps-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '蛇形步骤',
    suitableFor: ['长流程', '多步骤', '空间利用'],
    notSuitableFor: ['简单流程', '少于4步'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-snake-steps-compact-card',
    category: 'sequence',
    dataField: 'sequences',
    description: '紧凑蛇形卡片',
    suitableFor: ['长流程', '带描述的步骤'],
    notSuitableFor: ['简单流程', '少于4步'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-snake-steps-underline-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '下划线蛇形步骤',
    suitableFor: ['长流程', '强调文字'],
    notSuitableFor: ['简单流程', '少于4步'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-stairs-front-compact-card',
    category: 'sequence',
    dataField: 'sequences',
    description: '阶梯式卡片',
    suitableFor: ['递进过程', '成长阶段', '升级路径'],
    notSuitableFor: ['并列关系', '循环过程'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-stairs-front-pill-badge',
    category: 'sequence',
    dataField: 'sequences',
    description: '阶梯式徽章',
    suitableFor: ['递进过程', '等级展示'],
    notSuitableFor: ['并列关系', '循环过程'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-ascending-stairs-3d-underline-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '3D上升阶梯',
    suitableFor: ['递进过程', '成长展示', '视觉冲击'],
    notSuitableFor: ['并列关系', '简单列表'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-ascending-steps',
    category: 'sequence',
    dataField: 'sequences',
    description: '上升步骤',
    suitableFor: ['递进过程', '成长阶段'],
    notSuitableFor: ['并列关系', '循环过程'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-color-snake-steps-horizontal-icon-line',
    category: 'sequence',
    dataField: 'sequences',
    description: '彩色蛇形步骤',
    suitableFor: ['长流程', '视觉丰富'],
    notSuitableFor: ['简单流程', '严肃场景'],
    requiredFields: ['label'],
    optionalFields: ['desc', 'icon'],
  },
  {
    name: 'sequence-cylinders-3d-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '3D圆柱体流程',
    suitableFor: ['视觉冲击', '阶段展示'],
    notSuitableFor: ['简单内容', '大量文字'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-filter-mesh-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '筛选网格流程',
    suitableFor: ['筛选过程', '过滤展示'],
    notSuitableFor: ['非筛选场景', '并列关系'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-horizontal-zigzag-underline-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '水平之字形流程',
    suitableFor: ['长流程', '横向展示'],
    notSuitableFor: ['短流程', '垂直空间'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-mountain-underline-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '山峰轮廓流程',
    suitableFor: ['起伏过程', '高峰低谷'],
    notSuitableFor: ['线性递进', '并列关系'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-zigzag-pucks-3d-simple',
    category: 'sequence',
    dataField: 'sequences',
    description: '3D之字形圆盘',
    suitableFor: ['视觉丰富', '阶段展示'],
    notSuitableFor: ['简单内容', '大量文字'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },
  {
    name: 'sequence-zigzag-steps-underline-text',
    category: 'sequence',
    dataField: 'sequences',
    description: '之字形步骤',
    suitableFor: ['流程展示', '交替方向'],
    notSuitableFor: ['简单流程', '短步骤'],
    requiredFields: ['label'],
    optionalFields: ['desc'],
  },

  // ============ Compare Templates ============
  {
    name: 'compare-binary-horizontal-badge-card-arrow',
    category: 'compare',
    dataField: 'compares',
    description: '水平二元对比（徽章卡片箭头）',
    suitableFor: ['两方对比', '利弊分析', '好坏对比'],
    notSuitableFor: ['多方对比', '单一主题', '无对立关系'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'compare-binary-horizontal-simple-fold',
    category: 'compare',
    dataField: 'compares',
    description: '水平二元对比（折叠式）',
    suitableFor: ['两方对比', '简洁展示'],
    notSuitableFor: ['多方对比', '单一主题'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'compare-binary-horizontal-underline-text-vs',
    category: 'compare',
    dataField: 'compares',
    description: '水平二元对比（VS风格）',
    suitableFor: ['两方对比', '竞争对比', 'VS场景'],
    notSuitableFor: ['多方对比', '合作关系'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'compare-hierarchy-left-right-circle-node-pill-badge',
    category: 'compare',
    dataField: 'compares',
    description: '左右层级对比',
    suitableFor: ['层级对比', '组织对比', '结构对比'],
    notSuitableFor: ['简单二元', '无层级'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'compare-quadrant-quarter-simple-card',
    category: 'compare',
    dataField: 'compares',
    description: '四象限图（卡片式）',
    suitableFor: ['二维分类', '重要紧急矩阵', '四分类'],
    notSuitableFor: ['单维度', '非四分类'],
    requiredFields: ['label'],
    optionalFields: ['children', 'desc'],
  },
  {
    name: 'compare-quadrant-quarter-circular',
    category: 'compare',
    dataField: 'compares',
    description: '四象限图（圆形）',
    suitableFor: ['二维分类', '象限分析'],
    notSuitableFor: ['单维度', '非四分类'],
    requiredFields: ['label'],
    optionalFields: ['children', 'desc'],
  },
  {
    name: 'compare-swot',
    category: 'compare',
    dataField: 'compares',
    description: 'SWOT分析图',
    suitableFor: ['SWOT分析', '优劣势分析', '战略分析'],
    notSuitableFor: ['非四分类', '简单对比'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },

  // ============ Hierarchy Templates ============
  {
    name: 'hierarchy-tree-curved-line-rounded-rect-node',
    category: 'hierarchy',
    dataField: 'root',
    description: '曲线树状图',
    suitableFor: ['组织架构', '分类体系', '层级结构'],
    notSuitableFor: ['平行关系', '流程展示'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'hierarchy-tree-tech-style-badge-card',
    category: 'hierarchy',
    dataField: 'root',
    description: '科技风格树状图',
    suitableFor: ['技术架构', '系统结构'],
    notSuitableFor: ['平行关系', '流程展示'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'hierarchy-tree-tech-style-capsule-item',
    category: 'hierarchy',
    dataField: 'root',
    description: '胶囊风格树状图',
    suitableFor: ['层级结构', '分类展示'],
    notSuitableFor: ['平行关系', '流程展示'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'hierarchy-mindmap-branch-gradient-capsule-item',
    category: 'hierarchy',
    dataField: 'root',
    description: '渐变思维导图',
    suitableFor: ['发散思维', '主题拓展', '知识图谱'],
    notSuitableFor: ['严格层级', '流程展示'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'hierarchy-mindmap-level-gradient-compact-card',
    category: 'hierarchy',
    dataField: 'root',
    description: '层级渐变思维导图',
    suitableFor: ['思维导图', '概念发散'],
    notSuitableFor: ['严格层级', '流程展示'],
    requiredFields: ['label', 'children'],
    optionalFields: ['desc'],
  },
  {
    name: 'hierarchy-structure',
    category: 'hierarchy',
    dataField: 'items',
    description: '结构图',
    suitableFor: ['组织结构', '多层级展示', '分组展示'],
    notSuitableFor: ['平行关系', '简单列表'],
    requiredFields: ['label'],
    optionalFields: ['children', 'desc'],
  },

  // ============ Relation Templates ============
  {
    name: 'relation-dagre-flow-tb-simple-circle-node',
    category: 'relation',
    dataField: 'nodes',
    description: '流程关系图（圆形节点）',
    suitableFor: ['实体关系', '流程图', '依赖关系'],
    notSuitableFor: ['简单列表', '无关系数据'],
    requiredFields: ['id', 'label'],
    optionalFields: ['desc'],
  },
  {
    name: 'relation-dagre-flow-tb-badge-card',
    category: 'relation',
    dataField: 'nodes',
    description: '流程关系图（卡片节点）',
    suitableFor: ['复杂关系', '详细说明'],
    notSuitableFor: ['简单列表', '无关系数据'],
    requiredFields: ['id', 'label'],
    optionalFields: ['desc'],
  },
  {
    name: 'relation-dagre-flow-tb-animated-simple-circle-node',
    category: 'relation',
    dataField: 'nodes',
    description: '动画流程关系图（圆形节点）',
    suitableFor: ['动态展示', '流程演示'],
    notSuitableFor: ['静态场景', '打印场景'],
    requiredFields: ['id', 'label'],
    optionalFields: ['desc'],
  },
  {
    name: 'relation-dagre-flow-tb-animated-badge-card',
    category: 'relation',
    dataField: 'nodes',
    description: '动画流程关系图（卡片节点）',
    suitableFor: ['动态展示', '复杂流程演示'],
    notSuitableFor: ['静态场景', '打印场景'],
    requiredFields: ['id', 'label'],
    optionalFields: ['desc'],
  },
];

export const TEMPLATE_NAMES = TEMPLATES.map((t) => t.name);

export const TEMPLATES_BY_CATEGORY = TEMPLATES.reduce(
  (acc, template) => {
    if (!acc[template.category]) {
      acc[template.category] = [];
    }
    acc[template.category].push(template);
    return acc;
  },
  {} as Record<string, TemplateMetadata[]>
);

export function getTemplateMetadata(
  name: string
): TemplateMetadata | undefined {
  return TEMPLATES.find((t) => t.name === name);
}

export function getTemplatesByCategory(
  category: string
): TemplateMetadata[] {
  return TEMPLATES_BY_CATEGORY[category] || [];
}

export function getAlternativeTemplates(
  failedTemplate: string,
  triedTemplates: string[]
): string[] {
  const metadata = getTemplateMetadata(failedTemplate);
  if (!metadata) return [];

  return TEMPLATES.filter(
    (t) =>
      t.category === metadata.category &&
      t.name !== failedTemplate &&
      !triedTemplates.includes(t.name)
  ).map((t) => t.name);
}
